#!/bin/bash
DIR="$(dirname $0)"
cd "$DIR"

action=$1
object=$2
args="${@:3}"

echo "$0 $@" > ./start_event

[ "$object" = "head" ] && exec ./add-head.sh $action $args
[ "$object" = "sha1" ] && exec ./add-sha1.sh $action $args
