#!/bin/bash
DIR="$(dirname $0)"
cd "$DIR"

action=$1
object=$2
args="${@:3}"

[ "$action" == "build" ] && action="./autobuild.sh"
[ "$action" == "review" ] && action="./autoreview.sh"
[ "$object" == "head" ] && object="./add-head.sh"
[ "$object" == "sha1" ] && object="./add-sha1.sh"

exec $object $action $args
