#!/usr/bin/env python
import os
import sys
import getopt
import subprocess

# change-merged 
# --change <change id> 
# --change-url <change url> 
# --project <project name> 
# --branch <branch> 
# --topic <topic> 
# --submitter <submitter> 
# --commit <sha1>


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "",
                                   ["change=", "change-url=", "change-owner=", "project=",
                                    "branch=", "topic=", "submitter=", "commit="])
    except getopt.GetoptError, err:
        print >> sys.stderr, str(err)
        sys.exit(2)

    project = None
    commit = None

    for o, a in opts:
        if o == '--project':
            project = a
        elif o == '--commit':
            commit = a
        elif o == '--branch':
            branch = a

    print "send change merge to autobuilder:", project, branch, commit

    if project is None:
        print >> sys.stderr, "cannot find --project argument"
        sys.exit(2)

    if project == 'gfs':
        script = "/home/root1/autobuilder/start"
        command = "nohup /bin/bash -l -c \"%s %s %s > /home/root1/autobuilder/autobuilder.out 2>&1 < /dev/null &\"" % \
                  (script, "build head", branch)
        if '3.6' in branch:
            subprocess.call(["ssh", 'root@10.10.109.131', command])
        else:
            subprocess.call(["ssh", 'root@10.10.200.116', command])

    if project == 'xkv':
        script = "/home/root1/autobuilder/start"
        command = "nohup /bin/bash -l -c \"%s %s %s %s > /home/root1/autobuilder/autobuilder.out 2>&1 < /dev/null &\"" % \
                  (script, "build head", branch)
        subprocess.call(["ssh", 'root@10.10.200.115', command])

    print "complete building change merge:", project, branch, commit


if __name__ == '__main__':
    main()
